Updating Documentation
bentoml/transformers-nlp-service pull request #5
Opened 2023-05-03 15:18 UTC by jianshen92

- Adding a high level introduction
- Grouping content into subsections

2023-05-03 18:05 UTC, jianshen92 commented
Will add a gif in abit

2023-05-03 18:28 UTC, parano commented on .github/workflows/docker-push.yml
> +            TAG='transformer-nlp-service-gpu'
Let's make it consistent in the docs and image names, I think `transformers` is both referring to the huggingface library and saying it involves multiple transformers models in it's inference pipeline/graph, thus preferring that name

2023-05-04 06:37 UTC, aarnphm requested changes
intial comments

2023-05-04 06:37 UTC, aarnphm commented on .github/workflows/docker-push.yml
> +            TAG='transformers-nlp-service'
Can we change the tag here to 
```
TAG='${{ steps.repository.outputs.lowercase }}-gpu'
```
for first branch and
```
TAG='${{ steps.repository.outputs.lowercase }}'
```

so that we don't have to worry about this if we want to rename in the future

2023-05-04 06:37 UTC, aarnphm commented on README.md
> +### Bento CLI
```suggestion
### BentoCLI
```

2023-05-04 06:37 UTC, aarnphm commented on README.md
> +### Via BentoML Python Client 🐍
```suggestion
### Via BentoClient 🐍
```

2023-05-05 03:54 UTC, parano commented on README.md
> +server = bentoml.HTTPServer(bento, production=True, port=3000)
```suggestion
server = bentoml.HTTPServer(bento, port=3000)
```

production=True is becoming the default starting with the next release!

2023-05-07 19:56 UTC, aarnphm commented on README.md
> +server.start()
```suggestion
server = bentoml.HTTPServer(bento, port=3000, production=True)
server.start(blocking=True)
```

2023-05-07 19:57 UTC, aarnphm reviewed
One minor thing, and it is gtg

2023-05-07 23:44 UTC, parano commented on README.md
> +server.start()
I think we don't need `production=True` anymore?

2023-05-08 02:09 UTC, aarnphm commented on README.md
> +server.start()
You are right, since it is by default set to True.

But we probably still need blocking=True for this.

2023-05-08 17:29 UTC, parano commented on README.md
> +### BentoCLI
```suggestion
### BentoML CLI
```

To keep naming consistent with other docs. `bentoCLI` looks a bit similar to `bentoCTL`

2023-05-08 17:31 UTC, parano commented on README.md
> +bentoml build
1. Add `git clone`, `pip install -r ./requirements/pypi.txt`, here
2. Remove `bentoml build` step
3. Change the code below to 
```python
import bentoml

server = bentoml.HTTPServer("service:svc", port=3000)
server.start(blocking=True)
```

2023-05-08 17:31 UTC, parano commented on README.md
> +```
Link to BentoML gRPC docs here?

2023-05-08 17:41 UTC, jianshen92 commented on README.md
> +bentoml build
not sure about lines to create virtualenv, there's probably at least 5 different ways to create a virtualenv though. 

maybe state that : "it's recommended to run python within a virtual environment?"

2023-05-09 23:46 UTC, aarnphm commented on README.md
> +```
```suggestion
``` 

To find more information about gRPC with BentoML, refer to [our documentation](https://docs.bentoml.org/en/latest/guides/grpc.html)
```

2023-05-09 23:47 UTC, aarnphm commented on README.md
> +## 🌐 Interacting with the Service 🌐
```suggestion
To find more information about gRPC with BentoML, refer to [our documentation](https://docs.bentoml.org/en/latest/guides/grpc.html)

## 🌐 Interacting with the Service 🌐
```

2023-05-09 23:47 UTC, aarnphm approved these changes

2023-05-09 23:47 UTC, merged